NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY

XCACLS.EXE C:\CONTENTDELIVERY /T /G Administrators:F /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G DOMAIN\%1STR:C /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G DOMAIN\%1MGR:C /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G EVERYONE:R /Y