MD "C:\Reports"
MD C:\BACKUP
NET SHARE REPORTS /DELETE

MD "C:\Reports"

IF EXIST C:\WINDOWS\SYSTEM32\TZUTIL.EXE (GOTO WIN7) ELSE GOTO WXP

:WXP
NET SHARE BACKUP=C:\BACKUP
NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY
NET SHARE REPORTS="C:\Reports"
GOTO ACL

:WIN7
NET SHARE BACKUP=C:\BACKUP /GRANT:Everyone,FULL
NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY /GRANT:Everyone,FULL
NET SHARE REPORTS="C:\Reports" /GRANT:Everyone,FULL
GOTO ACL

:ACL
NET LOCALGROUP "REMOTE DESKTOP USERS" %1STR /ADD
NET LOCALGROUP "REMOTE DESKTOP USERS" %1MGR /ADD
NET LOCALGROUP "REMOTE DESKTOP USERS" %1FLASH /ADD

XCACLS.EXE C:\CONTENTDELIVERY /T /G Administrators:F /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G EVERYONE:R /Y

XCACLS.EXE C:\DOCUME~1\%1STR /T /G Administrators:F /Y
XCACLS.EXE C:\DOCUME~1\%1STR /T /E /G SYSTEM:F /Y
XCACLS.EXE C:\DOCUME~1\%1STR /T /E /G DOMAIN\%1STR:F /Y

XCACLS.EXE C:\DOCUME~1\%1MGR /T /G Administrators:F /Y
XCACLS.EXE C:\DOCUME~1\%1MGR /T /E /G SYSTEM:F /Y
XCACLS.EXE C:\DOCUME~1\%1MGR /T /E /G DOMAIN\%1MGR:F /Y

XCACLS.EXE C:\BACKUP /T /G Administrators:F /Y
XCACLS.EXE C:\BACKUP /T /E /G DOMAIN\%1STR:C /Y
XCACLS.EXE C:\BACKUP /T /E /G DOMAIN\%1MGR:C /Y

XCACLS.EXE C:\DARTS /T /G Administrators:F /Y
XCACLS.EXE C:\DARTS /T /E /G DOMAIN\%1STR:C /Y
XCACLS.EXE C:\DARTS /T /E /G DOMAIN\%1MGR:C /Y

XCACLS.EXE C:\DOCS /T /G Administrators:F /Y

XCACLS.EXE C:\RMOTXFR /T /G Administrators:F /Y
XCACLS.EXE C:\RMOTXFR /T /E /G DOMAIN\%1STR:C /Y
XCACLS.EXE C:\RMOTXFR /T /E /G DOMAIN\%1MGR:C /Y

XCACLS.EXE C:\REPORTS /T /G Administrators:F /Y
XCACLS.EXE C:\REPORTS /T /E /G EVERYONE:R /Y

at /delete /Y