for /f "tokens=1,2* delims=sS" %%i in ('echo %COMPUTERNAME%') do set SITE=%%i&set COMP=%%j
IF /I "%COMP%"=="T" GOTO STORE
GOTO END

:STORE
IF EXIST C:\temp\REGISTER.OPERATIONS.XR650.VBS GOTO XR650
IF EXIST C:\temp\REGISTER.OPERATIONS.1595.TEMP.VBS GOTO END
IF EXIST C:\temp\REGISTER.OPERATIONS.1595.AU.VBS GOTO END
IF EXIST C:\temp\REGISTER.OPERATIONS.1650.VBS GOTO 1650
GOTO END

:XR650
C:\temp\XR650.BAT
GOTO END

:1650
C:\temp\REGISTER.OPERATIONS.1650.VBS
GOTO END

:END
IF EXIST C:\temp\ACTIVATEJS.TXT C:\temp\POSTASKJS.BAT
EXIT