@ Echo Off
GOTO START

REM THIS FILE MAPS A DRIVE TO THE USERS OLD PROFILE, THEN COPIES ANY .NK2 FILE TO THEIR NEW PROFILE ON THE SERVER THEY ARE ON
REM IT THEN RUNS THE /IMPORTNK2 SWITCH WITH OUTLOOK.EXE TO IMOPRT THE NK2 FILE INTO THE SUGGESTED CONTACTS

:START

net use V: \\SERVER\SHARE\...\Outlook

if %ERRORLEVEL% NEQ 0 goto RUN

copy V:\*.nk2* %APPDATA%\Microsoft\Outlook\ /y

net use /delete V: /y

:RUN

start C:\"Program Files"\"Microsoft Office"\Office14\OUTLOOK.EXE /importnk2