for /f "tokens=1,2* delims=sS" %%i in ('echo %COMPUTERNAME%') do set SITE=%%i&set COMP=%%j
IF /I "%COMP%"=="T" GOTO STORE
IF /I "%COMP%"=="2" GOTO SHARE
GOTO END
:STORE
C:\temp\CONTENTDELIVERY.BAT
GOTO END
:SHARE
MD C:\CONTENTDELIVERY
NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY
XCACLS.EXE C:\CONTENTDELIVERY /T /G Administrators:F /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G EVERYONE:R /Y
:END
EXIT