################################################ ################################################
<#
.NOTES
Filename:   Generate-Monster-Report-For-All-Virtual-Machines.ps1
Version:    1.0
Author:     LucD, IT Admin
URL:        https://communities.vmware.com/t5/VMware-PowerCLI-Discussions/List-of-al-VMs-with-all-fields/td-p/447777

.DESCRIPTION
Script created to blueprint VMware environment
Output sent to Email with HTML table presenting results
Output sent to Csv

.EXAMPLE
<scriptName>.ps1

.HISTORY
Creation Date:  2021-12-02
Purpose/Change: Initial Script Development
#>
###########################################[INITIALIZATIONS ]#######################################
<#
[cmdletbinding()]
param
(
    [string]$param1
    [string]$<ParamName> = $(throw "[ERROR] : -<ParamName> parameter is required.")
    [ValidateSet('item1','item2')]
)
#>
$script:ScriptName = "<scriptName>.ps1"
$script:script_filepath = $MyInvocation.MyCommand.Path
$script:script_dir = Split-Path -Parent $script:script_filepath
$script:uid =([string](Get-Date -UFormat "%y%m%d") + ".ATM." + [string](Get-Random -Minimum 1000000000 -Maximum 9999999999))
$Script:ProductName = "<scriptName>"
$Script:Logfile = "$script:script_dir\logs\$($Script:ProductName).log"
$Script:FixMe = "$script:script_dir\logs\$($Script:ProductName)_FixMe.log"
if(!(Test-Path "$script:script_dir\logs")){mkdir "$script:script_dir\logs"}
if(Test-Path $Script:Logfile){Remove-Item $Script:Logfile}
$ErrorActionPreference = "SilentlyContinue"

## For SendGrid External SMTP Relay ##
$SendGridMailParams = @{
    #SendGrid Verified Sender Identity Created For This EMail Address
    From    =  "admin@example.com"
    To      =  "admin@example.com"
    #SendGrid APIKEY Generated By/For Verified Sender Identity
    APIKEY  =  "<apikey>"
    Subject =  "SendGrid Monster Report for All Virtual Machines 2"
    #Body    =  "This is a test email using SMTP Relay"
    Body    =  "C:\Temp\Monster-Report-For-All-Virtual-Machines.csv"
    #Body   =   $report
}
##############################################[FUNCTIONS]#############################################
Function Set-RunAsAdministrator()
{
  $CurrentUser = New-Object Security.Principal.WindowsPrincipal $([Security.Principal.WindowsIdentity]::GetCurrent())
    if($CurrentUser.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator))
  {
       Write-host "Script is running with Administrator privileges!"
  }
  else
    {
        $ElevatedProcess = New-Object System.Diagnostics.ProcessStartInfo "PowerShell";
        $ElevatedProcess.Arguments = "& '" + $script:MyInvocation.MyCommand.Path + "'"
        $ElevatedProcess.Verb = "runas"
        $ElevatedProcess.WindowStyle = "MINIMIZE"
       [System.Diagnostics.Process]::Start($ElevatedProcess)
       Exit
    }
}#=======================================[ End Function ]==========================================
Function Log_ToSplunk
{
    Param
    (
        [parameter(Mandatory=$true,Position=0)][String]$Message,
        [parameter(Mandatory=$false,Position=1)][String]$Type = "Log",
        [parameter(Mandatory=$false,Position=2)][String]$Status = "Informational",
        [parameter(Mandatory=$false,Position=3)][int]$ID = $Null
    )
    $product = "InfraEng_" + $Script:ProductName
    $uri = "https://hecext.example.com:18443/services/collector/event" #<-- UPDATE TO DOMAIN VALUE
    $header = @{}
    $header.add('Content-Type', 'application/json')
    $header.add('Authorization', 'Splunk Application-Key-Here')
    $body = @{
        sourcetype = 'DOMAIN:ps:log'
        host = $env:COMPUTERNAME
        event = @{
            message = $Message
            user = $env:USERNAME
            product = $Product
            type = $Type
            status = $Status
            id = $ID
            uid = $script:uid
        }
    }
    $body = $body | ConvertTo-Json
    Invoke-WebRequest -Uri $uri -Method Post -Headers $header -Body $body | Out-Null
}#=========================================[End Function]==========================================
Function Log-Append
{
    param
    (
        [parameter(Mandatory=$true,Position=0)][string]$message,
        [parameter(Mandatory=$false,Position=1)][string]$color
    )
    $ErrorActionPreference = "SilentlyContinue"
    $thetime = Get-Date -Format g
    Write-Host "$thetime`: $message" -ForegroundColor $color
    "$thetime`: $message" | Out-File $script:logfile -Append
}#=======================================[ End Function ]==========================================
Function Test-Prereqs
{
    param
    (
        [parameter(Mandatory=$true,Position=0)][string]$param1,
        [parameter(Mandatory=$false,Position=1)][string]$param2
    )

    #<--code-->
}#=======================================[ End Function ]==========================================
Function Send-EmailWithSendGrid {
    Param
        (
            [Parameter(Mandatory=$true)]
            [string] $From,
            [Parameter(Mandatory=$true)]
            [String] $To,
            [Parameter(Mandatory=$true)]
            [string] $ApiKey,
            [Parameter(Mandatory=$true)]
            [string] $Subject,
            [Parameter(Mandatory=$true)]
            [string] $Body
        )
   $headers = @{}
   $headers.Add("Authorization","Bearer $apiKey")
   $headers.Add("Content-Type", "application/json")
   $jsonRequest = [ordered]@{
        personalizations= @(@{to = @(@{email =  "$To"})
        subject = "$SubJect" })
        from = @{email = "$From"}
        content = @( @{ type = "text/plain"
                        value = "$Body" }
            )} | ConvertTo-Json -Depth 10
   Invoke-RestMethod   -Uri "https://api.sendgrid.com/v3/mail/send" -Method Post -Headers $headers -Body $jsonRequest
}#=======================================[ End Function ]==========================================

#########################################[ SCRIPT STARTS ]#########################################
Set-RunAsAdministrator
Clear-Host
$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
$stopwatch.Start()
Log-Append -message "[BEGIN]"
#--------------------------------------------------------------------------------------------------

#Import PowerCLI Module - Note: Unable To Import In VSCode's Powershell Core Module
#Import-Module VMware.PowerCLI

#Connect to VMware vCenter Instance
Connect-VIServer -Server "srvvcenterp.example.com" -Protocol https

#If applicable, Set Invalid Certificate Action - Enable If Environment Requires It
##Set-PowerCLIConfiguration -Scope AllUsers -ParticipateInCeip $false -InvalidCertificateAction $false

#Gathering VM settings
Write-Host "Gathering VM statistics"

#Generate Report For All Virtual Machines
$report = @()
foreach($vm in Get-View -ViewType Virtualmachine){
    $vms = "" | Select-Object VMName, Hostname, IPAddress, OS, Boottime, VMState, TotalCPU, CPUAffinity,
        CPUHotAdd, CPUShare, CPUlimit, OverallCpuUsage, CPUreservation, TotalMemory, MemoryShare, MemoryUsage,
        MemoryHotAdd, MemoryLimit, MemoryReservation, Swapped, Ballooned, Compressed, TotalNics, ToolsStatus,
        ToolsVersion, HardwareVersion, TimeSync, CBT, Portgroup, VMHost, ProvisionedSpaceGB, UsedSpaceGB, Datastore,
        FaultTolerance, SnapshotName, SnapshotDate, SnapshotSizeGB, Tags, NB_last_backup, Notes

    $vms.VMName = $vm.Name
    $vms.Hostname = $vm.guest.hostname
    $vms.IPAddress = $vm.guest.ipAddress
    $vms.OS = $vm.Config.GuestFullName
    $vms.Boottime = $vm.Runtime.BootTime
    $vms.VMState = $vm.summary.runtime.powerState
    $vms.TotalCPU = $vm.summary.config.numcpu
    $vms.CPUAffinity = $vm.Config.CpuAffinity
    $vms.CPUHotAdd = $vm.Config.CpuHotAddEnabled
    $vms.CPUShare = $vm.Config.CpuAllocation.Shares.Level
    $vms.TotalMemory = $vm.summary.config.memorysizemb
    $vms.MemoryHotAdd = $vm.Config.MemoryHotAddEnabled
    $vms.MemoryShare = $vm.Config.MemoryAllocation.Shares.Level
    $vms.TotalNics = $vm.summary.config.numEthernetCards
    $vms.OverallCpuUsage = $vm.summary.quickStats.OverallCpuUsage
    $vms.MemoryUsage = $vm.summary.quickStats.guestMemoryUsage
    $vms.ToolsStatus = $vm.guest.toolsstatus
    $vms.ToolsVersion = $vm.config.tools.toolsversion
    $vms.TimeSync = $vm.Config.Tools.SyncTimeWithHost
    $vms.HardwareVersion = $vm.config.Version
    $vms.MemoryLimit = $vm.resourceconfig.memoryallocation.limit
    $vms.MemoryReservation = $vm.resourceconfig.memoryallocation.reservation
    $vms.CPUreservation = $vm.resourceconfig.cpuallocation.reservation
    $vms.CPUlimit = $vm.resourceconfig.cpuallocation.limit
    $vms.CBT = $vm.Config.ChangeTrackingEnabled
    $vms.Swapped = $vm.Summary.QuickStats.SwappedMemory
    $vms.Ballooned = $vm.Summary.QuickStats.BalloonedMemory
    $vms.Compressed = $vm.Summary.QuickStats.CompressedMemory
    $vms.Portgroup = Get-View -Id $vm.Network -Property Name | Select-Object -ExpandProperty Name
    $vms.VMHost = Get-View -Id $vm.Runtime.Host -Property Name | Select-Object -ExpandProperty Name
    $vms.ProvisionedSpaceGB = [math]::Round($vm.Summary.Storage.UnCommitted/1GB,2)
    $vms.UsedSpaceGB = [math]::Round($vm.Summary.Storage.Committed/1GB,2)
    $vms.Datastore = $vm.Config.DatastoreUrl[0].Name
    $vms.Notes = $vm.Config.Annotation
    $vms.FaultTolerance = $vm.Runtime.FaultToleranceState
    $vms.SnapshotName = &{$script:snaps = Get-Snapshot -VM $vm.Name; $script:snaps.Name -join ','}
    $vms.SnapshotDate = $script:snaps.Created -join ','
    $vms.SnapshotSizeGB = $script:snaps.SizeGB -join ','
    $vms.Tags = (Get-TagAssignment -Entity $vm.Name).Tag.Name -join ','
    $vms.NB_last_backup = Get-VM -Name $vm.Name | Select-Object -ExpandProperty Customfields | Where-Object {$_.Key -eq 'NB Last Backup'} | Select-Object -ExpandProperty Value
    $Report += $vms
}

#Output to Csv
$report | Export-Csv "C:\Temp\2021-Monster-Report-For-All-Virtual-Machines.csv" -NoTypeInformation -NoClobber
#if ($GridView -eq "yes") {$report | Out-GridView }
#if ($CreateCSV -eq "yes") {$report | Export-Csv "C:\Temp\Monster-Report-For-All-Virtual-Machines.csv" -NoTypeInformation -NoClobber}

#Output to Email Using External SMTP Relay
#Send-EmailWithSendGrid @SendGridMailParams

#Output to Email Using Internal SMTP Relay
#Send-MailMessage -From 'Automated Report <smtp-relay.example.com>' -To 'IT Admin <admin@example.com>' -Subject 'Internal Monster Report for All Virtual Machines' `
#-BodyAsHtml -Attachments "C:\Temp\Monster-Report-For-All-Virtual-Machines.csv" -Priority High -DeliveryNotificationOption OnSuccess, OnFailure -SmtpServer 'smtp-relay.example.com'

<#
Send-MailMessage -From 'Automated Report <smtp-relay.example.com>' -To 'IT Admin <admin@example.com>' -Subject 'Internal Monster Report for All Virtual Machines' `
-BodyAsHtml -Body ($report | ConvertTo-Html | Out-String) -Priority High -DeliveryNotificationOption OnSuccess, OnFailure -SmtpServer 'smtp-relay.example.com'
#>

#--------------------------------------------------------------------------------------------------
# Clean up and exit
$elapsed = [math]::Round($stopwatch.Elapsed.TotalMinutes,2)
$stopwatch.Stop()
Log-Append -message "[STATUS] : Script Completion.TTC = $($elapsed) Minutes."
EXIT
#########################################[ SCRIPT ENDS ]###########################################
