MD C:\CONTENTDELIVERY
NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY
XCACLS.EXE C:\CONTENTDELIVERY /T /G Administrators:F /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G EVERYONE:R /Y
CD C:\
CD SCRIPTS
CONTENT.DELIVERY.VBS
IF EXIST \\%SITE%J2\C$\ ROBOCOPY C:\CONTENTDELIVERY\ \\%SITE%J2\C$\...\ /MIR /R:4 /W:60 /NP >>C:\CONTENTDELIVERY.LOG
IF EXIST \\%SITE%J2\C$\ ROBOCOPY C:\REPORTS\ \\%SITE%J2\C$\...\ /MIR /R:4 /W:60 /NP >>C:\CONTENTDELIVERY.LOG