MD C:\CONTENTDELIVERY
NET SHARE CONTENTDELIVERY=C:\CONTENTDELIVERY
XCACLS.EXE C:\CONTENTDELIVERY /T /G Administrators:F /Y
XCACLS.EXE C:\CONTENTDELIVERY /T /E /G EVERYONE:R /Y

ROBOCOPY \\SERVER\SHARE\...\ C:\CONTENTDELIVERY\ /E /R:4 /W:60
ROBOCOPY \\SERVER\SHARE\...\ C:\DOCUME~1\ALLUSE~1\STARTM~1\PROGRAMS\ *.LNK /E /R:4 /W:60

ECHO CONTENT SYNCHRONIZATION COMPLETE
PAUSE